export const MOOVIES_SEARCH_FIELD_CHANGE = 'MOOVIES_SEARCH_FIELD_CHANGE'
export const SET_MOOVIES_SEARCH_FIELD_CHANGE = 'SET_MOOVIES_SEARCH_FIELD_CHANGE'

export const GET_MOOVIES_REQUEST = 'GET_MOOVIES_REQUEST'
export const GET_MOOVIES_SUCCESS = 'GET_MOOVIES_SUCCESS'
export const GET_MOOVIES_FAILURE = 'GET_MOOVIES_FAILURE'
