name: CI

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Lint and Unit Test
      run: |
        npm install
        npm run lint
        npm test
        npm run build
